import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { createPortal } from 'react-dom'
import './AdminEmailTemplatesPage.css'
import { useDialogFocus } from '../hooks/useDialogFocus'
import EmailTriggersPanel from './EmailTriggersPanel'

type ApiRequest = (path: string, options?: RequestInit, tokenOverride?: string) => Promise<any>
type EmailTemplate = { id?: number | string; template_key: string; template_name: string; subject_template: string; html_body: string; text_body?: string; active: boolean; updated_at?: string }
type Form = Omit<EmailTemplate, 'id' | 'updated_at'>
const blank: Form = { template_key: '', template_name: '', subject_template: '', html_body: '', text_body: '', active: true }
const endpoint = '/api/admin/email'
const errorText = (e: unknown) => e instanceof Error ? e.message : 'Something went wrong. Please try again.'
const interpolate = (value: string, vars: Record<string, unknown>) => value.replace(/{{\s*([\w.-]+)\s*}}/g, (_, key) => String(vars[key] ?? `{{${key}}}`))
const splitRecipients = (value: string) => value.split(/[\n,]+/).map(item => item.trim()).filter(Boolean)

export default function AdminEmailTemplatesPage({ apiRequest }: { apiRequest: ApiRequest }) {
  const [items, setItems] = useState<EmailTemplate[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const [editing, setEditing] = useState<EmailTemplate | null>(null); const [sending, setSending] = useState<EmailTemplate | null>(null)
  const apiRequestRef = useRef(apiRequest)
  useEffect(() => { apiRequestRef.current = apiRequest }, [apiRequest])
  const load = useCallback(async () => { setLoading(true); setError(''); try { const r = await apiRequestRef.current(`${endpoint}/templates`); setItems(Array.isArray(r?.data) ? r.data : []) } catch (e) { setError(errorText(e)) } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  const toggle = async (item: EmailTemplate) => { try { await apiRequestRef.current(`${endpoint}/templates/${encodeURIComponent(item.template_key)}/${item.active ? 'disable' : 'enable'}`, { method: 'POST', body: '{}' }); await load() } catch (e) { setError(errorText(e)) } }
  return <div className="adm-page admin-aligned-page email-templates-page">
    <header className="adm-header dashboard-section-head"><div className="adm-header__title"><p className="et-eyebrow">Administration / Delivery</p><h1 className="adm-heading">Email templates</h1><p className="et-subheading">Reusable, database-backed messages for every module. Recipients and variables are supplied only at send time.</p></div><div className="adm-header__actions"><button className="adm-btn adm-btn--icon" onClick={() => void load()} aria-label="Reload templates">↻</button><button className="adm-btn adm-btn--primary" onClick={() => setEditing({ ...blank })}>+ New template</button></div></header>
    {error && <div className="et-notice" role="alert">{error}</div>}
    <section className="adm-table-card table-card"><div className="adm-table-toolbar"><div className="adm-table-title"><strong>{items.length} {items.length === 1 ? 'template' : 'templates'}</strong><span>Template keys are used by all modules</span></div></div>
    {loading ? <div className="adm-empty empty-state"><strong>Loading templates…</strong></div> : items.length ? <div className="adm-table-scroll table-scroll"><table className="adm-table dashboard-table"><thead><tr><th>Template</th><th>Key</th><th>Status</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{items.map(item => <tr key={item.template_key}><td><span className="adm-cell-primary">{item.template_name}</span></td><td><code className="et-key">{item.template_key}</code></td><td><span className={`adm-pill table-pill adm-pill--${item.active ? 'active' : 'inactive'}`}>{item.active ? 'Enabled' : 'Disabled'}</span></td><td className="adm-cell-secondary">{item.updated_at ? new Date(item.updated_at).toLocaleString() : '—'}</td><td><div className="adm-actions"><button className="adm-action-btn" onClick={() => setEditing(item)}>Edit</button><button className="adm-action-btn" onClick={() => void toggle(item)}>{item.active ? 'Disable' : 'Enable'}</button><button className="adm-action-btn adm-action-btn--view" onClick={() => setSending(item)}>Send</button></div></td></tr>)}</tbody></table></div> : <div className="adm-empty empty-state"><strong>No templates yet</strong><span>Create a reusable message for any application module.</span><button className="adm-btn adm-btn--primary" onClick={() => setEditing({ ...blank })}>New template</button></div>}</section>
    <EmailTriggersPanel apiRequest={apiRequest} templateKeys={items.map(item => item.template_key)}/>
    {editing && createPortal(<Editor template={editing} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); void load() }} apiRequest={apiRequest}/>, document.body)}
    {sending && createPortal(<SendDialog template={sending} onClose={() => setSending(null)} apiRequest={apiRequest}/>, document.body)}
  </div>
}

function Editor({ template, onClose, onSaved, apiRequest }: { template: EmailTemplate; onClose: () => void; onSaved: () => void; apiRequest: ApiRequest }) {
 const dialogRef = useRef<HTMLElement | null>(null); useDialogFocus({ containerRef: dialogRef, open: true, onClose })
 const [form, setForm] = useState<Form>({ ...blank, ...template }); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [varsText, setVarsText] = useState('{\n  "name": "Preview value"\n}')
 const vars = useMemo(() => { try { const parsed = JSON.parse(varsText); return parsed && typeof parsed === 'object' ? parsed : {} } catch { return {} } }, [varsText])
 const change = <K extends keyof Form>(key: K, value: Form[K]) => setForm(old => ({ ...old, [key]: value }))
 const save = async () => { if (!form.template_key.trim() || !form.template_name.trim()) return setError('Template key and name are required.'); setSaving(true); setError(''); try { const isNew = !template.id; await apiRequest(`${endpoint}/templates${isNew ? '' : `/${encodeURIComponent(template.template_key)}`}`, { method: isNew ? 'POST' : 'PUT', body: JSON.stringify(form) }); onSaved() } catch(e) { setError(errorText(e)) } finally { setSaving(false) } }
 return <div className="et-overlay" role="dialog" aria-modal="true" aria-label="Email template editor"><section className="et-drawer" ref={dialogRef}><header className="et-drawer-head"><div><p className="et-eyebrow">Template editor</p><h2>{template.id ? 'Edit template' : 'New template'}</h2></div><button className="et-close" onClick={onClose} aria-label="Close">×</button></header>{error && <div className="et-notice" role="alert">{error}</div>}<div className="et-editor-grid"><form className="et-form" onSubmit={e => { e.preventDefault(); void save() }}><label>Template key<input value={form.template_key} disabled={Boolean(template.id)} onChange={e => change('template_key', e.target.value)} placeholder="GENERIC_TEMPLATE_KEY"/></label><label>Template name<input value={form.template_name} onChange={e => change('template_name', e.target.value)}/></label><label className="et-toggle"><input type="checkbox" checked={form.active} onChange={e => change('active', e.target.checked)}/><span>Template is enabled</span></label><label>Subject template<input value={form.subject_template} onChange={e => change('subject_template', e.target.value)} placeholder="{{title}}"/></label><label>HTML body<textarea value={form.html_body} onChange={e => change('html_body', e.target.value)} rows={10}/></label><label>Plain-text body <span className="et-muted">optional</span><textarea value={form.text_body || ''} onChange={e => change('text_body', e.target.value)} rows={6}/></label><p className="et-help">Use placeholders such as <code>{'{{name}}'}</code>. Values are supplied dynamically when sending.</p><footer><button type="button" className="adm-btn" onClick={onClose}>Cancel</button><button className="adm-btn adm-btn--primary" disabled={saving}>{saving ? 'Saving…' : 'Save template'}</button></footer></form><aside className="et-preview"><div><p className="et-eyebrow">Safe preview</p><h3>Local preview</h3><p>Substitutions are shown as text only.</p></div><label>Preview variables JSON<textarea value={varsText} onChange={e => setVarsText(e.target.value)} rows={5}/></label><div className="et-mail"><strong>{interpolate(form.subject_template, vars) || 'Subject preview'}</strong><hr/><pre>{interpolate(form.html_body, vars) || 'Your HTML template preview will appear here.'}</pre></div></aside></div></section></div>
}

function SendDialog({ template, onClose, apiRequest }: { template: EmailTemplate; onClose: () => void; apiRequest: ApiRequest }) { const dialogRef = useRef<HTMLElement | null>(null); useDialogFocus({ containerRef: dialogRef, open: true, onClose }); const [to,setTo]=useState(''); const [cc,setCc]=useState(''); const [bcc,setBcc]=useState(''); const [variables,setVariables]=useState('{}'); const [sourceService,setSourceService]=useState(''); const [referenceId,setReferenceId]=useState(''); const [state,setState]=useState<{error?:string;success?:boolean}>({}); const [busy,setBusy]=useState(false); const send=async()=>{let parsed:Record<string,unknown>;try{parsed=JSON.parse(variables)}catch{return setState({error:'Variables must be valid JSON.'})}setBusy(true);setState({});try{await apiRequest(`${endpoint}/send`,{method:'POST',body:JSON.stringify({templateKey:template.template_key,to:splitRecipients(to),cc:splitRecipients(cc),bcc:splitRecipients(bcc),variables:parsed,sourceService:sourceService||undefined,referenceId:referenceId||undefined})});setState({success:true});setBcc('')}catch(e){setState({error:errorText(e)})}finally{setBusy(false)}};return <div className="et-overlay" role="dialog" aria-modal="true" aria-label="Send template"><section className="et-dialog" ref={dialogRef}><header className="et-drawer-head"><div><p className="et-eyebrow">Manual trigger</p><h2>Send “{template.template_name}”</h2></div><button className="et-close" onClick={onClose} aria-label="Close">×</button></header>{state.success ? <div className="et-success" role="status">Email submitted for delivery. BCC recipients are not displayed.</div> : <div className="et-form"><label>To<textarea value={to} onChange={e=>setTo(e.target.value)} rows={2} placeholder="Separate addresses with commas or new lines"/></label><label>CC <span className="et-muted">optional</span><textarea value={cc} onChange={e=>setCc(e.target.value)} rows={2}/></label><label>BCC <span className="et-muted">optional</span><textarea value={bcc} onChange={e=>setBcc(e.target.value)} rows={2}/></label><label>Variables JSON<textarea value={variables} onChange={e=>setVariables(e.target.value)} rows={5}/></label><label>Source service <input value={sourceService} onChange={e=>setSourceService(e.target.value)}/></label><label>Reference ID <input value={referenceId} onChange={e=>setReferenceId(e.target.value)}/></label>{state.error&&<div className="et-notice" role="alert">{state.error}</div>}<footer><button className="adm-btn" onClick={onClose}>Cancel</button><button className="adm-btn adm-btn--primary" onClick={()=>void send()} disabled={busy}>{busy?'Sending…':'Send email'}</button></footer></div>}</section></div> }
