import type {
  EmployeeMasterResourceConfig,
  EmployeeMasterResourceKey,
  EmployeeMasterSidebarId,
  SidebarId,
} from '../../../types/admin'

export const EMPLOYEE_MASTER_STATUS_OPTIONS = [
  { value: 'active', label: 'Active' },
  { value: 'inactive', label: 'Inactive' },
]

const statusField = {
  key: 'status',
  label: 'Status',
  required: true,
  type: 'select' as const,
  options: EMPLOYEE_MASTER_STATUS_OPTIONS,
}

const descriptionField = {
  key: 'description',
  label: 'Description',
  type: 'textarea' as const,
  placeholder: 'Optional operational notes',
}

export const employeeMasterResourceConfigs: Record<EmployeeMasterResourceKey, EmployeeMasterResourceConfig> = {
  workingUnits: {
    key: 'workingUnits',
    sidebarId: 'employee-master-working-units',
    title: 'Working Units',
    tabLabel: 'Working Units',
    singularLabel: 'Working Unit',
    endpoint: '/api/admin/employee-master/working-units',
    codeField: 'unit_code',
    nameField: 'unit_name',
    hasLocationPicker: true,
    tableColumns: [
      { key: 'unit_name', label: 'Unit Name', kind: 'primary', minWidth: 220 },
      { key: 'unit_code', label: 'Unit Code', kind: 'code', minWidth: 130 },
      { key: 'address', label: 'Address', minWidth: 260 },
      { key: 'city', label: 'City', minWidth: 140 },
      { key: 'state', label: 'State', minWidth: 140 },
      { key: 'country', label: 'Country', minWidth: 140 },
      { key: 'pincode', label: 'Pincode', minWidth: 120 },
      { key: 'latitude', label: 'Latitude', minWidth: 130 },
      { key: 'longitude', label: 'Longitude', minWidth: 130 },
      { key: 'geofence_radius', label: 'Geofence Radius', minWidth: 160 },
      { key: 'branch_site_name', label: 'Branch / Site Name', minWidth: 190 },
      { key: 'shift_mapping_id', label: 'Shift Mapping ID', minWidth: 160 },
      { key: 'status', label: 'Status', kind: 'status', minWidth: 120 },
      { key: 'created_by', label: 'Created By', minWidth: 150 },
      { key: 'created_date', label: 'Created Date', minWidth: 150 },
    ],
    formFields: [
      {
        key: 'unit_name',
        label: 'Unit Name',
        required: true,
        placeholder: 'Corporate Office',
      },
      {
        key: 'unit_code',
        label: 'Unit Code',
        required: true,
        placeholder: 'WU-001',
      },
      {
        key: 'address',
        label: 'Address',
        type: 'textarea',
        placeholder: 'Street address',
      },
      {
        key: 'city',
        label: 'City',
        optionKey: 'cities',
        placeholder: 'Bengaluru',
      },
      {
        key: 'state',
        label: 'State',
        optionKey: 'states',
        placeholder: 'Karnataka',
      },
      {
        key: 'country',
        label: 'Country',
        optionKey: 'countries',
        placeholder: 'India',
      },
      {
        key: 'pincode',
        label: 'Pincode',
        placeholder: '560001',
      },
      {
        key: 'latitude',
        label: 'Latitude',
        inputType: 'number',
        placeholder: '12.971599',
      },
      {
        key: 'longitude',
        label: 'Longitude',
        inputType: 'number',
        placeholder: '77.594566',
      },
      {
        key: 'geofence_radius',
        label: 'Geofence Radius',
        inputType: 'number',
        placeholder: '100',
      },
      {
        key: 'branch_site_name',
        label: 'Branch / Site Name',
        placeholder: 'Main Branch',
      },
      {
        key: 'shift_mapping_id',
        label: 'Shift Mapping ID',
        inputType: 'number',
        placeholder: '1',
      },
      statusField,
    ],
    filters: [
      {
        stateKey: 'city',
        param: 'city',
        label: 'City',
        optionKey: 'cities',
        recordField: 'city',
      },
      {
        stateKey: 'state',
        param: 'state',
        label: 'State',
        optionKey: 'states',
        recordField: 'state',
      },
      {
        stateKey: 'country',
        param: 'country',
        label: 'Country',
        optionKey: 'countries',
        recordField: 'country',
      },
    ],
  },
  payrollUnits: {
    key: 'payrollUnits',
    sidebarId: 'employee-master-payroll-units',
    title: 'Payroll Units',
    tabLabel: 'Payroll Units',
    singularLabel: 'Payroll Unit',
    endpoint: '/api/admin/employee-master/payroll-units',
    codeField: 'unit_code',
    nameField: 'unit_name',
    tableColumns: [
      { key: 'unit_name', label: 'Unit Name', kind: 'primary', minWidth: 220 },
      { key: 'unit_code', label: 'Unit Code', kind: 'code', minWidth: 130 },
      { key: 'legal_entity_name', label: 'Legal Entity Name', minWidth: 220 },
      { key: 'pay_group_id', label: 'Pay Group ID', minWidth: 140 },
      { key: 'pan_tax_id', label: 'PAN / Tax ID', minWidth: 150 },
      { key: 'gst_registration_no', label: 'GST Registration No', minWidth: 190 },
      { key: 'pf_registration_no', label: 'PF Registration No', minWidth: 180 },
      { key: 'esi_registration_no', label: 'ESI Registration No', minWidth: 180 },
      { key: 'bank_name', label: 'Bank Name', minWidth: 170 },
      { key: 'bank_account_no', label: 'Bank Account No', minWidth: 180 },
      { key: 'ifsc_swift_code', label: 'IFSC / SWIFT Code', minWidth: 170 },
      { key: 'payslip_template_id', label: 'Payslip Template ID', minWidth: 180 },
      { key: 'pay_cycle', label: 'Pay Cycle', minWidth: 140 },
      { key: 'status', label: 'Status', kind: 'status', minWidth: 120 },
      { key: 'created_by', label: 'Created By', minWidth: 150 },
      { key: 'created_date', label: 'Created Date', minWidth: 150 },
    ],
    formFields: [
      {
        key: 'unit_name',
        label: 'Unit Name',
        required: true,
        placeholder: 'Monthly India Payroll',
      },
      {
        key: 'unit_code',
        label: 'Unit Code',
        required: true,
        placeholder: 'PU-001',
      },
      {
        key: 'legal_entity_name',
        label: 'Legal Entity Name',
        placeholder: 'Fawnix Technologies Pvt Ltd',
      },
      {
        key: 'pay_group_id',
        label: 'Pay Group ID',
        inputType: 'number',
        placeholder: '1',
      },
      {
        key: 'pan_tax_id',
        label: 'PAN / Tax ID',
        placeholder: 'ABCDE1234F',
      },
      {
        key: 'gst_registration_no',
        label: 'GST Registration No',
        placeholder: '29ABCDE1234F1Z5',
      },
      {
        key: 'pf_registration_no',
        label: 'PF Registration No',
        placeholder: 'PF registration number',
      },
      {
        key: 'esi_registration_no',
        label: 'ESI Registration No',
        placeholder: 'ESI registration number',
      },
      {
        key: 'bank_name',
        label: 'Bank Name',
        placeholder: 'HDFC Bank',
      },
      {
        key: 'bank_account_no',
        label: 'Bank Account No',
        placeholder: 'Account number',
      },
      {
        key: 'ifsc_swift_code',
        label: 'IFSC / SWIFT Code',
        placeholder: 'HDFC0000001',
      },
      {
        key: 'payslip_template_id',
        label: 'Payslip Template ID',
        inputType: 'number',
        placeholder: '1',
      },
      {
        key: 'pay_cycle',
        label: 'Pay Cycle',
        optionKey: 'pay_cycles',
        placeholder: 'Monthly',
      },
      statusField,
    ],
    filters: [
      {
        stateKey: 'payGroupId',
        param: 'pay_group_id',
        label: 'Pay Group',
        optionKey: 'pay_group_ids',
        recordField: 'pay_group_id',
      },
      {
        stateKey: 'payCycle',
        param: 'pay_cycle',
        label: 'Pay Cycle',
        optionKey: 'pay_cycles',
        recordField: 'pay_cycle',
      },
    ],
  },
  designations: {
    key: 'designations',
    sidebarId: 'employee-master-designations',
    title: 'Designations',
    tabLabel: 'Designations',
    singularLabel: 'Designation',
    endpoint: '/api/admin/employee-master/designations',
    codeField: 'designation_code',
    nameField: 'designation_name',
    tableColumns: [
      { key: 'designation_name', label: 'Designation', kind: 'primary', minWidth: 220 },
      { key: 'designation_code', label: 'Code', kind: 'code', minWidth: 120 },
      { key: 'job_level_grade', label: 'Job Level / Grade', minWidth: 160 },
      { key: 'department', label: 'Department', minWidth: 180 },
      { key: 'status', label: 'Status', kind: 'status', minWidth: 120 },
      { key: 'description', label: 'Description', minWidth: 240 },
    ],
    formFields: [
      {
        key: 'designation_code',
        label: 'Designation Code',
        required: true,
        placeholder: 'DES-001',
      },
      {
        key: 'designation_name',
        label: 'Designation Name',
        required: true,
        placeholder: 'Senior Executive',
      },
      {
        key: 'job_level_grade',
        label: 'Job Level / Grade',
        required: true,
        optionKey: 'job_level_grades',
        placeholder: 'L3',
      },
      {
        key: 'department',
        label: 'Department',
        required: true,
        optionKey: 'departments',
        placeholder: 'Operations',
      },
      statusField,
      descriptionField,
    ],
    filters: [
      {
        stateKey: 'jobLevelGrade',
        param: 'job_level_grade',
        label: 'Job Level',
        optionKey: 'job_level_grades',
        recordField: 'job_level_grade',
      },
      {
        stateKey: 'department',
        param: 'department',
        label: 'Department',
        optionKey: 'departments',
        recordField: 'department',
      },
    ],
  },
  departments: {
    key: 'departments',
    sidebarId: 'employee-master-departments',
    title: 'Departments',
    tabLabel: 'Departments',
    singularLabel: 'Department',
    endpoint: '/api/admin/employee-master/departments',
    codeField: 'department_code',
    nameField: 'department_name',
    tableColumns: [
      { key: 'department_name', label: 'Department', kind: 'primary', minWidth: 220 },
      { key: 'department_code', label: 'Code', kind: 'code', minWidth: 120 },
      { key: 'department_head', label: 'Department Head', minWidth: 180 },
      { key: 'parent_department', label: 'Parent Department', minWidth: 180 },
      { key: 'working_unit', label: 'Working Unit', minWidth: 180 },
      { key: 'location', label: 'Location', minWidth: 160 },
      { key: 'status', label: 'Status', kind: 'status', minWidth: 120 },
      { key: 'description', label: 'Description', minWidth: 240 },
    ],
    formFields: [
      {
        key: 'department_code',
        label: 'Department Code',
        required: true,
        placeholder: 'DEP-001',
      },
      {
        key: 'department_name',
        label: 'Department Name',
        required: true,
        placeholder: 'Customer Success',
      },
      {
        key: 'department_head',
        label: 'Department Head',
        required: true,
        optionKey: 'department_heads',
        placeholder: 'Head name or code',
      },
      {
        key: 'working_unit',
        label: 'Working Unit',
        required: true,
        optionKey: 'working_units',
        placeholder: 'Corporate Office',
      },
      {
        key: 'location',
        label: 'Location',
        required: true,
        optionKey: 'locations',
        placeholder: 'Bengaluru',
      },
      {
        key: 'parent_department',
        label: 'Parent Department',
        optionKey: 'parent_departments',
        placeholder: 'Optional parent',
      },
      statusField,
      descriptionField,
    ],
    filters: [
      {
        stateKey: 'workingUnit',
        param: 'working_unit',
        label: 'Working Unit',
        optionKey: 'working_units',
        recordField: 'working_unit',
      },
      {
        stateKey: 'location',
        param: 'location',
        label: 'Location',
        optionKey: 'locations',
        recordField: 'location',
      },
      {
        stateKey: 'parentDepartment',
        param: 'parent_department',
        label: 'Parent',
        optionKey: 'parent_departments',
        recordField: 'parent_department',
      },
    ],
  },
}

export const employeeMasterResources = Object.values(employeeMasterResourceConfigs)

export function getEmployeeMasterResourceByPanel(panel: SidebarId): EmployeeMasterResourceConfig | null {
  return employeeMasterResources.find((resource) => resource.sidebarId === panel) || null
}

export function isEmployeeMasterSidebarId(panel: SidebarId): panel is EmployeeMasterSidebarId {
  return employeeMasterResources.some((resource) => resource.sidebarId === panel)
}
