"""
AWS S3 storage helpers for meeting-notes assets.
"""

from __future__ import annotations

from datetime import datetime
from io import BytesIO
import logging
import re
from typing import Any, Dict
import uuid

from config import Config

logger = logging.getLogger(__name__)

try:
    import boto3
except ImportError:  # pragma: no cover - optional dependency
    boto3 = None

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import ListFlowable, ListItem, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
except ImportError:  # pragma: no cover - optional dependency
    colors = None
    A4 = None
    ParagraphStyle = None
    getSampleStyleSheet = None
    inch = None
    ListFlowable = None
    ListItem = None
    Paragraph = None
    SimpleDocTemplate = None
    Spacer = None
    Table = None
    TableStyle = None


def is_s3_configured() -> bool:
    """Return True when S3 credentials are available."""
    return bool(
        boto3 is not None
        and Config.MEETING_NOTES_S3_BUCKET
        and Config.MEETING_NOTES_AWS_ACCESS_KEY_ID
        and Config.MEETING_NOTES_AWS_SECRET_ACCESS_KEY
        and Config.MEETING_NOTES_S3_REGION
    )


def _build_s3_client():
    if boto3 is None:
        raise RuntimeError("boto3 package is not installed")

    return boto3.client(
        "s3",
        region_name=Config.MEETING_NOTES_S3_REGION,
        aws_access_key_id=Config.MEETING_NOTES_AWS_ACCESS_KEY_ID,
        aws_secret_access_key=Config.MEETING_NOTES_AWS_SECRET_ACCESS_KEY,
    )


def _safe_slug(value: str | None, fallback: str) -> str:
    raw = (value or "").strip().lower()
    if not raw:
        return fallback
    cleaned = re.sub(r"[^a-z0-9]+", "-", raw).strip("-")
    return cleaned[:80] or fallback


def _build_object_name(prefix: str, filename: str, emp_code: str | None, meeting_title: str | None) -> str:
    original_filename = (filename or "").strip() or "meeting-file"
    extension = ""
    if "." in original_filename:
        extension = "." + original_filename.rsplit(".", 1)[-1].strip().lower()

    timestamp = datetime.utcnow()
    return (
        f"{prefix}/{timestamp.strftime('%Y/%m/%d')}/"
        f"{_safe_slug(emp_code, 'unknown-employee')}/"
        f"{_safe_slug(meeting_title, 'meeting')}-{uuid.uuid4().hex}{extension}"
    )


def _public_url(bucket_name: str, object_name: str) -> str:
    region = Config.MEETING_NOTES_S3_REGION
    return f"https://{bucket_name}.s3.{region}.amazonaws.com/{object_name}"


def _escape_text(value: Any) -> str:
    text = str(value or "").strip()
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _pdf_paragraphs_from_multiline(text: str, style) -> list:
    paragraphs = []
    for block in [segment.strip() for segment in str(text or "").splitlines() if segment.strip()]:
        paragraphs.append(Paragraph(_escape_text(block), style))
        paragraphs.append(Spacer(1, 0.08 * inch))
    if not paragraphs:
        paragraphs.append(Paragraph("No content available.", style))
    return paragraphs


def _build_meeting_report_pdf(
    report_payload: Dict[str, Any],
    *,
    generated_at: datetime,
) -> bytes:
    if SimpleDocTemplate is None:
        raise RuntimeError("reportlab package is not installed")

    buffer = BytesIO()
    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=0.65 * inch,
        leftMargin=0.65 * inch,
        topMargin=0.7 * inch,
        bottomMargin=0.65 * inch,
    )
    styles = getSampleStyleSheet()
    title_style = styles["Title"]
    heading_style = styles["Heading2"]
    body_style = styles["BodyText"]
    body_style.leading = 15
    body_style.spaceAfter = 6
    meta_style = ParagraphStyle(
        "MetaStyle",
        parent=styles["BodyText"],
        fontSize=10,
        textColor=colors.HexColor("#4b5563"),
        leading=13,
    )

    story = [
        Paragraph("Fawnix Meeting Notes Report", title_style),
        Spacer(1, 0.12 * inch),
    ]

    metadata_rows = [
        ["Meeting Title", _escape_text(report_payload.get("meeting_title") or "Untitled meeting")],
        ["Source Audio", _escape_text(report_payload.get("file_name") or "Uploaded audio")],
        ["Generated By", _escape_text(report_payload.get("provider") or "AI provider")],
        ["Generated At", generated_at.strftime("%d %b %Y, %I:%M %p UTC")],
    ]
    story.append(
        Table(
            metadata_rows,
            colWidths=[1.5 * inch, 4.7 * inch],
            style=TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), colors.whitesmoke),
                    ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#d1d5db")),
                    ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e5e7eb")),
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#111827")),
                    ("TEXTCOLOR", (1, 0), (1, -1), colors.HexColor("#374151")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]
            ),
        )
    )
    story.append(Spacer(1, 0.22 * inch))

    story.append(Paragraph("Executive Summary", heading_style))
    story.extend(_pdf_paragraphs_from_multiline(report_payload.get("summary") or "", body_style))
    story.append(Spacer(1, 0.12 * inch))

    story.append(Paragraph("Minutes of Meeting", heading_style))
    story.extend(_pdf_paragraphs_from_multiline(report_payload.get("minutes_of_meeting") or "", body_style))
    story.append(Spacer(1, 0.12 * inch))

    story.append(Paragraph("Important Points", heading_style))
    important_points = report_payload.get("important_points") or []
    if important_points:
        story.append(
            ListFlowable(
                [
                    ListItem(Paragraph(_escape_text(point), body_style))
                    for point in important_points
                    if str(point).strip()
                ],
                bulletType="bullet",
                leftIndent=14,
            )
        )
    else:
        story.append(Paragraph("No important points were extracted.", body_style))
    story.append(Spacer(1, 0.16 * inch))

    story.append(Paragraph("Transcript", heading_style))
    transcript_text = str(report_payload.get("transcript") or "").strip()
    story.extend(_pdf_paragraphs_from_multiline(transcript_text, meta_style))

    document.build(story)
    return buffer.getvalue()


def upload_meeting_audio(
    audio_bytes: bytes,
    filename: str,
    *,
    content_type: str | None = None,
    emp_code: str | None = None,
    meeting_title: str | None = None,
) -> Dict[str, Any]:
    """Upload meeting audio bytes to S3 and return object metadata."""
    if not is_s3_configured():
        raise RuntimeError("S3 is not configured")

    bucket_name = Config.MEETING_NOTES_S3_BUCKET
    object_name = _build_object_name(
        Config.MEETING_NOTES_S3_AUDIO_PREFIX,
        filename,
        emp_code,
        meeting_title,
    )
    client = _build_s3_client()
    client.upload_fileobj(
        Fileobj=BytesIO(audio_bytes),
        Bucket=bucket_name,
        Key=object_name,
        ExtraArgs={"ContentType": content_type or "application/octet-stream"},
    )

    return {
        "bucket": bucket_name,
        "object_name": object_name,
        "file_name": (filename or "").strip() or "meeting-audio",
        "content_type": content_type or "application/octet-stream",
        "size_bytes": len(audio_bytes),
        "url": _public_url(bucket_name, object_name),
        "folder": Config.MEETING_NOTES_S3_AUDIO_PREFIX,
        "provider": "s3",
    }


def upload_meeting_report(
    report_payload: Dict[str, Any],
    *,
    emp_code: str | None = None,
    meeting_title: str | None = None,
) -> Dict[str, Any]:
    """Upload generated meeting report PDF to S3 and return object metadata."""
    if not is_s3_configured():
        raise RuntimeError("S3 is not configured")

    generated_at = datetime.utcnow()
    report_filename = f"{_safe_slug(meeting_title, 'meeting-report')}.pdf"
    object_name = _build_object_name(
        Config.MEETING_NOTES_S3_REPORT_PREFIX,
        report_filename,
        emp_code,
        meeting_title,
    )
    report_bytes = _build_meeting_report_pdf(report_payload, generated_at=generated_at)
    bucket_name = Config.MEETING_NOTES_S3_BUCKET
    client = _build_s3_client()
    client.upload_fileobj(
        Fileobj=BytesIO(report_bytes),
        Bucket=bucket_name,
        Key=object_name,
        ExtraArgs={
            "ContentType": "application/pdf",
            "ContentDisposition": f'attachment; filename="{report_filename}"',
        },
    )

    return {
        "bucket": bucket_name,
        "object_name": object_name,
        "file_name": report_filename,
        "content_type": "application/pdf",
        "size_bytes": len(report_bytes),
        "url": _public_url(bucket_name, object_name),
        "folder": Config.MEETING_NOTES_S3_REPORT_PREFIX,
        "provider": "s3",
        "download_url": _public_url(bucket_name, object_name),
    }
